pull_request_rules:
  - name: Request reviews and label Steward's PRs
    conditions:
      - author=scala-steward
    actions:
      request_reviews:
        users: [ Odomontois, catostrophe, oskin1, danslapman, funfunfine ]
      label:
        add: [ dependency-update ]

  - name: Merge Steward's PRs
    conditions:
      - author=scala-steward
      - or:
          - and:
              - "#files=1"
              - or:
                  - files=project/build.properties
                  - files=project/plugins.sbt
          - body~=labels:.*semver-patch
          - "#approved-reviews-by>=1"
      - and:
          - check-success~=Test \(ubuntu-latest, 2\.12\.\d+, adopt@1\.8\)
          - check-success~=Test \(ubuntu-latest, 2\.12\.\d+, adopt@1\.11\)
          - check-success~=Test \(ubuntu-latest, 2\.13\.\d+, adopt@1\.8\)
          - check-success~=Test \(ubuntu-latest, 2\.13\.\d+, adopt@1\.11\)
    actions:
      merge:
        method: rebase

  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
